version: '3'

services:
  music-management:
    build: music_streaming
    ports:
    - "3000:3000"
    - "27017:27017"
    - "9229:9229"
    volumes:
    - /Users/oskarspozdnakovs/pozdnako-y3/website:/usr/src/website
    - mongoData:/data/db
    - /Users/oskarspozdnakovs/pozdnako-y3/docker_mm_nm:/usr/src/app/node_modules
    environment:
      MONGO_CONN_STR: "mongodb://localhost:27017/songs"

volumes:
  mongoData:
  node_modules:
